/**
 * Process-level command-reference generation: pinned Usage markdown,
 * README managed-section update/check, and public-doc inventory.
 */

import { spawnSync } from "node:child_process"
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import {
  generateCommandReference,
  runCheckUsageDocs,
  runUpdateUsageDocs,
} from "../scripts/update-usage-docs.ts"
import { describe, expect, test } from "bun:test"

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const workspaceRoot = resolve(appRoot, "../..")
const usageSpecPath = join(appRoot, "ready-for-agent.usage.kdl")
const pinnedUsage = join(workspaceRoot, "scripts", "run-pinned-usage.sh")
const publicReadmePath = join(workspaceRoot, "README.md")

const PUBLIC_COMMANDS = [
  "start",
  "add",
  "candidates",
  "intake",
  "retry",
  "status",
  "jump",
  "skills",
] as const

const REPOSITORY_SELECTOR_FORMS = [
  "<forge-host>://<project-path>",
  "<forge-host>/<project-path>",
  "unique project path",
  "unique final project-path segment",
] as const

const INTERNAL_TOKENS = [
  "--ready-for-agent-internal-github-helper",
  "--ready-for-agent-internal-gitlab-helper",
  "--ready-for-agent-internal-azure-devops-helper",
  "--ready-for-agent-internal-keymaxxer-sidecar",
] as const

const USAGE_START_MARKER = "<!-- usage:start -->"
const USAGE_END_MARKER = "<!-- usage:end -->"

const runPinnedMarkdown = (): string => {
  const result = spawnSync(
    "bash",
    [pinnedUsage, "generate", "markdown", "-f", usageSpecPath],
    {
      cwd: workspaceRoot,
      encoding: "utf8",
      env: {
        ...process.env,
        NO_COLOR: "1",
      },
    },
  )
  expect(result.status, result.stderr).toBe(0)
  return result.stdout
}

const fixtureReadme = (managed: string): string =>
  `# Ready for Agent

## Quick start

npx ready-for-agent@latest

## Command reference

${USAGE_START_MARKER}
${managed.endsWith("\n") ? managed : `${managed}\n`}${USAGE_END_MARKER}

## Troubleshooting

hand-written
`

const writeFixture = (managed: string): string => {
  const root = mkdtempSync(join(tmpdir(), "ready-for-agent-usage-docs-"))
  const readmePath = join(root, "README.md")
  writeFileSync(readmePath, fixtureReadme(managed))
  return readmePath
}

const extractManagedSection = (readme: string): string => {
  const start = readme.indexOf(USAGE_START_MARKER)
  const end = readme.indexOf(USAGE_END_MARKER)
  expect(start).toBeGreaterThanOrEqual(0)
  expect(end).toBeGreaterThan(start)
  return readme.slice(start + USAGE_START_MARKER.length, end).replace(/^\n/, "")
}

describe("operator CLI command-reference documentation", () => {
  test("generation uses the pinned Usage CLI and matches its markdown", () => {
    const version = spawnSync("bash", [pinnedUsage, "--version"], {
      encoding: "utf8",
    })
    expect(version.status, version.stderr).toBe(0)
    expect(version.stdout).toContain("5.1.0")

    const generated = generateCommandReference()
    expect(generated).toBe(runPinnedMarkdown())
    expect(generated.startsWith("<!-- @generated by usage-cli")).toBe(true)
  })

  test("update refreshes only the Usage-managed README section", () => {
    const readmePath = writeFixture("stale command reference\n")
    try {
      const before = readFileSync(readmePath, "utf8")
      runUpdateUsageDocs({ readmePath })
      const after = readFileSync(readmePath, "utf8")

      expect(after).not.toBe(before)
      expect(after).toContain("## Quick start")
      expect(after).toContain("npx ready-for-agent@latest")
      expect(after).toContain("## Troubleshooting")
      expect(after).toContain("hand-written")
      expect(extractManagedSection(after)).toBe(runPinnedMarkdown())
      expect(after.indexOf(USAGE_START_MARKER)).toBe(
        before.indexOf(USAGE_START_MARKER),
      )
    } finally {
      rmSync(dirname(readmePath), { recursive: true, force: true })
    }
  })

  test("check generates into temporary storage and does not rewrite a current README", () => {
    const generated = runPinnedMarkdown()
    const readmePath = writeFixture(generated)
    try {
      const before = readFileSync(readmePath)
      const result = runCheckUsageDocs({ readmePath })
      expect(result).toEqual({ kind: "ok" })
      expect(readFileSync(readmePath).equals(before)).toBe(true)
    } finally {
      rmSync(dirname(readmePath), { recursive: true, force: true })
    }
  })

  test("check fails and leaves the README untouched when the reference is stale", () => {
    const readmePath = writeFixture("stale command reference\n")
    try {
      const before = readFileSync(readmePath)
      const result = runCheckUsageDocs({ readmePath })
      expect(result).toEqual({ kind: "stale" })
      expect(readFileSync(readmePath).equals(before)).toBe(true)
    } finally {
      rmSync(dirname(readmePath), { recursive: true, force: true })
    }
  })

  test("check fails when generated markdown is nondeterministic", () => {
    const generated = runPinnedMarkdown()
    const readmePath = writeFixture(generated)
    try {
      let calls = 0
      const result = runCheckUsageDocs({
        readmePath,
        generate: () => {
          calls += 1
          return calls === 1 ? generated : `${generated}\n# drift\n`
        },
      })
      expect(result).toEqual({ kind: "nondeterministic" })
      expect(readFileSync(readmePath, "utf8")).toBe(fixtureReadme(generated))
    } finally {
      rmSync(dirname(readmePath), { recursive: true, force: true })
    }
  })

  test("checked-in README command reference covers the public operator CLI", () => {
    const readme = readFileSync(publicReadmePath, "utf8")
    const managed = extractManagedSection(readme)

    expect(readme).toContain("## Quick start")
    expect(readme).toContain("## Requirements")
    expect(readme).toContain("## Features")
    expect(readme).toContain("## How it works")
    expect(readme).toContain("## Configuration")
    expect(managed).toBe(runPinnedMarkdown())

    expect(managed).toContain("# `ready-for-agent`")
    for (const name of PUBLIC_COMMANDS) {
      expect(managed).toContain(`## \`ready-for-agent ${name}\``)
    }

    expect(managed).toContain("### `-h --help`")
    expect(managed).toContain("### `-v --version`")
    expect(managed).toContain("### `--completions <shell>`")
    expect(managed).toContain("### `--log-level <level>`")
    expect(managed).toContain("### `--no-open`")
    expect(managed).toContain("### `--host [addr]`")
    expect(managed).toContain("#### `<path>`")
    expect(managed).toContain("#### `<repository>`")
    expect(managed).toContain("#### `[repository]`")
    expect(managed).toContain("#### `<session-id>`")
    expect(managed).toContain("#### `--forge-host <host>`")
    expect(managed).toContain("#### `--project-path <project-path>`")
    expect(managed).toContain("#### `--issue <id>`")
    expect(managed).toContain("#### `--work-item <id>`")
    expect(managed).toContain("#### `--all-retryable`")
    expect(managed).toContain("#### `--max-autonomous-retries <count>`")

    expect(managed).toContain("**Effect**: modifies state")
    expect(managed).toContain("**Effect**: read-only")
    expect(managed).toContain(
      "**Effect**: destructive — may delete or irreversibly overwrite",
    )

    expect(managed).toContain("```\nready-for-agent\n```")
    expect(managed).toContain("```\nready-for-agent start --no-open\n```")
    expect(managed).toContain(
      "```\nready-for-agent add /path/to/local/repo\n```",
    )
    expect(managed).toContain(
      "```\nready-for-agent candidates github.com/owner/repo\n```",
    )
    expect(managed).toContain(
      "```\nready-for-agent candidates github.com://owner/repo\n```",
    )
    expect(managed).toContain("```\nready-for-agent candidates owner/repo\n```")
    expect(managed).toContain("```\nready-for-agent candidates repo\n```")
    expect(managed).toContain(
      "```\nready-for-agent intake github.com/owner/repo\n```",
    )
    expect(managed).toContain(
      "```\nready-for-agent retry github.com/owner/repo --all-retryable\n```",
    )
    expect(managed).toContain("```\nready-for-agent status\n```")
    expect(managed).toContain(
      "```\nready-for-agent jump 85312e9f-9c57-42ef-9757-b2512cee57cd\n```",
    )
    expect(managed).toContain("```\nready-for-agent skills\n```")
    expect(managed).toContain("```\nready-for-agent skills list --json\n```")
    expect(managed).toContain("```\nready-for-agent skills get core\n```")
    expect(managed).toContain("#### `<skill-id>`")
    expect(managed).toContain("#### `--json`")

    expect(managed).toContain("NO_BROWSER")
    expect(managed).toContain("HOST")
    expect(managed).toContain("READY_FOR_AGENT_GRAPHQL_URL")
    for (const form of REPOSITORY_SELECTOR_FORMS) {
      expect(managed).toContain(form)
    }
    expect(managed.toLowerCase()).toContain("case-insensitive")
  })

  test("checked-in command reference omits hidden metadata and internal helpers", () => {
    const managed = extractManagedSection(
      readFileSync(publicReadmePath, "utf8"),
    )
    expect(managed).not.toContain("--usage")
    expect(managed).not.toContain("--no-no-open")
    for (const token of INTERNAL_TOKENS) {
      expect(managed).not.toContain(token)
    }
  })

  test("check CLI exits 0 without rewriting the public README", () => {
    const before = readFileSync(publicReadmePath)
    const result = spawnSync(
      "bun",
      [
        "--conditions",
        "@ready-for-agent/source",
        "scripts/update-usage-docs.ts",
        "--check",
      ],
      {
        cwd: appRoot,
        encoding: "utf8",
      },
    )
    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0)
    expect(readFileSync(publicReadmePath).equals(before)).toBe(true)
  })

  test("Nx update and check targets keep generation explicit and non-writing", async () => {
    const project = JSON.parse(
      await readFileSync(join(appRoot, "project.json"), "utf8"),
    ) as {
      targets: Record<
        string,
        {
          command?: string
          options?: { command?: string }
          cache?: boolean
          inputs?: unknown[]
          outputs?: unknown[]
          dependsOn?: unknown[]
        }
      >
    }

    const update = project.targets["update-usage-docs"]
    const check = project.targets["check-usage-docs"]
    expect(update?.options?.command ?? update?.command).toContain(
      "scripts/update-usage-docs.ts",
    )
    expect(update?.options?.command ?? update?.command).not.toContain("--check")
    expect(update?.outputs).toContain("{workspaceRoot}/README.md")
    expect(update?.cache).toBe(false)

    expect(check?.options?.command ?? check?.command).toContain(
      "scripts/update-usage-docs.ts",
    )
    expect(check?.options?.command ?? check?.command).toContain("--check")
    expect(check?.outputs ?? []).not.toContain("{workspaceRoot}/README.md")
    expect(JSON.stringify(check?.inputs ?? [])).toContain("README.md")
    expect(JSON.stringify(check?.inputs ?? [])).toContain(
      "ready-for-agent.usage.kdl",
    )
    expect(JSON.stringify(check?.inputs ?? [])).toContain("run-pinned-usage.sh")

    expect(project.targets.test?.dependsOn).toEqual(
      expect.arrayContaining(["check-usage"]),
    )
  })
})
