import { Context, type Duration, type Effect } from "effect"
import type { PlatformError } from "effect/PlatformError"
import type { SqlError } from "effect/unstable/sql/SqlError"
import type { AgentBackendNotInstalledError } from "@ready-for-agent/agent-backend"
import type {
  AzureDevOpsNotImplementedError,
  AzureDevOpsProjectUnavailableError,
  AzureDevOpsRequestError,
} from "@ready-for-agent/azure-devops-service"
import type {
  DatabaseError,
  RepositoryNotFoundError,
} from "@ready-for-agent/db-service"
import type { MergePullRequestResult } from "@ready-for-agent/forge-contract"
import type {
  GitHubRepositoryUnavailableError,
  GitHubRequestError,
  GitHubThrottledError,
  GitHubTlsTrustError,
} from "@ready-for-agent/github-service"
import type {
  GitLabProjectUnavailableError,
  GitLabRequestError,
} from "@ready-for-agent/gitlab-service"
import type { KeymaxxerError } from "@ready-for-agent/keymaxxer-service"
import type {
  LinearNotConfiguredError,
  LinearRequestError,
} from "@ready-for-agent/linear-service"
import type { AssessChangesResult } from "./assess-changes.js"
import type { AssessChangesError } from "./assess-changes-errors.js"
import type { CloseIssueError } from "./close-issue-errors.js"
import type { CommitResult } from "./commit.js"
import type { CommitError } from "./commit-errors.js"
import type { CreatePrResult } from "./create-pr.js"
import type { CreatePrError } from "./create-pr-errors.js"
import type { CreateWorktreeError } from "./create-worktree-errors.js"
import type {
  DecidePrMergeContextError,
  DecidePrMergeOpenCodeError,
  DecidePrMergeResult,
} from "./decide-pr-merge.js"
import type {
  LifecycleStepFailedError,
  WorkItemLifecycleDatabaseError,
} from "./errors.js"
import type { ImplementError } from "./implement-errors.js"
import type { InstallDependenciesError } from "./install-dependencies-errors.js"
import type { MarkPrReadyForReviewResult } from "./mark-pr-ready-for-review.js"
import type { MarkPrReadyForReviewError } from "./mark-pr-ready-for-review-errors.js"
import type { MergePrContextError } from "./merge-pr.js"
import type {
  PrStatusCheckInvestigationResult,
  PrStatusCheckResult,
  PrStatusChecksContextError,
  PrStatusChecksOpenCodeError,
  PrStatusChecksUnresolvedError,
} from "./pr-status-checks.js"
import type { PreCommitError } from "./pre-commit-errors.js"
import type { RemoveWorktreeError } from "./remove-worktree.js"
import type {
  ResolvePrMergeConflictContextError,
  ResolvePrMergeConflictOpenCodeError,
  ResolvePrMergeConflictResult,
} from "./resolve-pr-merge-conflict.js"
import type { ReviewResult } from "./review.js"
import type { ReviewError } from "./review-errors.js"
import type { IssueSource, MergeMode, WorkItemId } from "./types.js"

/**
 * Context supplied to every Lifecycle Step handler.
 * Later steps receive worktree/session fields persisted by earlier successes.
 */
export interface LifecycleStepContext {
  readonly workItemId: WorkItemId
  readonly repositoryId: string
  readonly issueNumber: number
  /**
   * Original Issue Source captured on the Work Item. Issue reads, prompt
   * identity, links, mutations, and source credentials resolve against this
   * rather than the Repository's current Issue Tracker. Absent only for
   * legacy step-handler tests; production always sets it.
   */
  readonly issueSource?: IssueSource
  /**
   * Issue title captured on the Work Item for identification after the Issue
   * leaves the store.
   */
  readonly issueTitle: string | null
  /**
   * Work Item captured Agent Backend id (provenance for Agent Turns and
   * operator-visible failure copy).
   */
  readonly agentBackend: string
  readonly model: string
  readonly thinkingLevel: string | null
  readonly reviewModel: string
  readonly reviewThinkingLevel: string | null
  readonly worktreePath: string | null
  readonly startingCommitOid: string | null
  readonly completionSummary: string | null
  /**
   * Canonical publication title/body shared by Commit and Create PR when set.
   * Generated by Commit before the first native mutation.
   */
  readonly publicationTitle: string | null
  readonly publicationBody: string | null
  readonly sessionId: string | null
  /**
   * Work Item Auto-merge override. Null/omitted follows Repository Auto-merge.
   */
  readonly autoMergeOverride?: boolean | null
  /**
   * Durable Merge Mode. `always` is the Always pin and accepts post-deadline
   * `no_checks` at Merge PR revalidation.
   */
  readonly mergeMode?: MergeMode
  readonly maxDuration?: Duration.Duration
}

/** Result of a successful Create Worktree Step Run. */
export type CreateWorktreeResult = {
  readonly worktreePath: string
  readonly startingCommitOid: string
}

/**
 * Typed failures a Lifecycle Step handler may surface to the orchestrator.
 * Domain step errors plus platform/service errors that production handlers
 * currently leave unmapped.
 */
export type LifecycleStepError =
  | CreateWorktreeError
  | InstallDependenciesError
  | ImplementError
  | AssessChangesError
  | PreCommitError
  | ReviewError
  | CommitError
  | CreatePrError
  | CloseIssueError
  | RemoveWorktreeError
  | DecidePrMergeContextError
  | DecidePrMergeOpenCodeError
  | PrStatusChecksContextError
  | PrStatusChecksOpenCodeError
  | PrStatusChecksUnresolvedError
  | ResolvePrMergeConflictContextError
  | ResolvePrMergeConflictOpenCodeError
  | MarkPrReadyForReviewError
  | MergePrContextError
  | LifecycleStepFailedError
  | DatabaseError
  | RepositoryNotFoundError
  | GitHubRequestError
  | GitHubTlsTrustError
  | AgentBackendNotInstalledError
  | GitHubThrottledError
  | GitHubRepositoryUnavailableError
  | GitLabRequestError
  | GitLabProjectUnavailableError
  | AzureDevOpsRequestError
  | AzureDevOpsProjectUnavailableError
  | AzureDevOpsNotImplementedError
  | LinearRequestError
  | LinearNotConfiguredError
  | KeymaxxerError
  | PlatformError
  | SqlError

/** Errors runHandler may surface, including orchestrator DB reads mid-handler. */
export type RunHandlerError =
  | LifecycleStepError
  | WorkItemLifecycleDatabaseError

/**
 * Injected step handlers. Production adapters and tests both implement this
 * surface; the lifecycle module selects the handler from the pending step.
 */
export interface LifecycleStepsShape {
  readonly createWorktree: (
    context: LifecycleStepContext,
  ) => Effect.Effect<CreateWorktreeResult, LifecycleStepError>
  readonly installDependencies: (
    context: LifecycleStepContext,
  ) => Effect.Effect<void, LifecycleStepError>
  readonly implement: (
    context: LifecycleStepContext,
  ) => Effect.Effect<string, LifecycleStepError>
  readonly assessChanges: (
    context: LifecycleStepContext,
  ) => Effect.Effect<AssessChangesResult, LifecycleStepError>
  readonly preCommit: (
    context: LifecycleStepContext,
  ) => Effect.Effect<void, LifecycleStepError>
  readonly review: (
    context: LifecycleStepContext,
  ) => Effect.Effect<ReviewResult, LifecycleStepError>
  readonly commit: (
    context: LifecycleStepContext,
  ) => Effect.Effect<CommitResult, LifecycleStepError>
  readonly createPr: (
    context: LifecycleStepContext,
  ) => Effect.Effect<CreatePrResult, LifecycleStepError>
  readonly watchPrStatusChecks: (
    context: LifecycleStepContext,
  ) => Effect.Effect<PrStatusCheckResult, LifecycleStepError>
  readonly resolvePrMergeConflict: (
    context: LifecycleStepContext,
  ) => Effect.Effect<ResolvePrMergeConflictResult, LifecycleStepError>
  readonly investigatePrStatusChecks: (
    context: LifecycleStepContext,
  ) => Effect.Effect<PrStatusCheckInvestigationResult, LifecycleStepError>
  readonly markPrReadyForReview: (
    context: LifecycleStepContext,
  ) => Effect.Effect<MarkPrReadyForReviewResult, LifecycleStepError>
  readonly decidePrMerge: (
    context: LifecycleStepContext,
  ) => Effect.Effect<DecidePrMergeResult, LifecycleStepError>
  readonly mergePr: (
    context: LifecycleStepContext,
  ) => Effect.Effect<MergePullRequestResult, LifecycleStepError>
  readonly closeIssue: (
    context: LifecycleStepContext,
  ) => Effect.Effect<void, LifecycleStepError>
  readonly localCleanup: (
    context: LifecycleStepContext,
  ) => Effect.Effect<void, LifecycleStepError>
  readonly removeWorktree: (
    context: LifecycleStepContext,
  ) => Effect.Effect<void, LifecycleStepError>
}

export class LifecycleSteps extends Context.Service<
  LifecycleSteps,
  LifecycleStepsShape
>()("@ready-for-agent/work-item-lifecycle/LifecycleSteps") {}
